# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import srv6_path_pb2 as srv6__path__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in srv6_path_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SRv6PathServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestPath = channel.unary_unary(
                '/srv6path.SRv6PathService/RequestPath',
                request_serializer=srv6__path__pb2.PathRequest.SerializeToString,
                response_deserializer=srv6__path__pb2.MultiplePathsResponse.FromString,
                _registered_method=True)
        self.InstallPath = channel.unary_unary(
                '/srv6path.SRv6PathService/InstallPath',
                request_serializer=srv6__path__pb2.InstallPathRequest.SerializeToString,
                response_deserializer=srv6__path__pb2.PathResponse.FromString,
                _registered_method=True)
        self.ConfirmInstallation = channel.unary_unary(
                '/srv6path.SRv6PathService/ConfirmInstallation',
                request_serializer=srv6__path__pb2.InstallConfirm.SerializeToString,
                response_deserializer=srv6__path__pb2.InstallResponse.FromString,
                _registered_method=True)


class SRv6PathServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmInstallation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SRv6PathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestPath': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPath,
                    request_deserializer=srv6__path__pb2.PathRequest.FromString,
                    response_serializer=srv6__path__pb2.MultiplePathsResponse.SerializeToString,
            ),
            'InstallPath': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallPath,
                    request_deserializer=srv6__path__pb2.InstallPathRequest.FromString,
                    response_serializer=srv6__path__pb2.PathResponse.SerializeToString,
            ),
            'ConfirmInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmInstallation,
                    request_deserializer=srv6__path__pb2.InstallConfirm.FromString,
                    response_serializer=srv6__path__pb2.InstallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srv6path.SRv6PathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('srv6path.SRv6PathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SRv6PathService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srv6path.SRv6PathService/RequestPath',
            srv6__path__pb2.PathRequest.SerializeToString,
            srv6__path__pb2.MultiplePathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srv6path.SRv6PathService/InstallPath',
            srv6__path__pb2.InstallPathRequest.SerializeToString,
            srv6__path__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srv6path.SRv6PathService/ConfirmInstallation',
            srv6__path__pb2.InstallConfirm.SerializeToString,
            srv6__path__pb2.InstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
