# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bgp_segments.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bgp_segments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62gp_segments.proto\x12\x0c\x62gp_segments\"\x9a\x01\n\x0e\x42gpDataRequest\x12\x11\n\tlocal_asn\x18\x01 \x01(\r\x12\'\n\x08segments\x18\x02 \x03(\x0b\x32\x15.bgp_segments.Segment\x12#\n\x05paths\x18\x03 \x03(\x0b\x32\x14.bgp_segments.AsPath\x12\'\n\x08networks\x18\x04 \x03(\x0b\x32\x15.bgp_segments.Network\"R\n\x0f\x42gpDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1d\n\x15total_segments_stored\x18\x03 \x01(\r\"%\n\x07Segment\x12\x0c\n\x04\x61s_a\x18\x01 \x01(\r\x12\x0c\n\x04\x61s_b\x18\x02 \x01(\r\"\x1d\n\x06\x41sPath\x12\x13\n\x0b\x61s_sequence\x18\x01 \x03(\r\">\n\x07Network\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\x0f\n\x07is_ipv6\x18\x03 \x01(\x08\x32`\n\x0e\x42gpPathService\x12N\n\rReportBgpData\x12\x1c.bgp_segments.BgpDataRequest\x1a\x1d.bgp_segments.BgpDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bgp_segments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BGPDATAREQUEST']._serialized_start=37
  _globals['_BGPDATAREQUEST']._serialized_end=191
  _globals['_BGPDATARESPONSE']._serialized_start=193
  _globals['_BGPDATARESPONSE']._serialized_end=275
  _globals['_SEGMENT']._serialized_start=277
  _globals['_SEGMENT']._serialized_end=314
  _globals['_ASPATH']._serialized_start=316
  _globals['_ASPATH']._serialized_end=345
  _globals['_NETWORK']._serialized_start=347
  _globals['_NETWORK']._serialized_end=409
  _globals['_BGPPATHSERVICE']._serialized_start=411
  _globals['_BGPPATHSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
